version: '3.8'

services:
  analyticsmicroservice:
    image: analyticsmicroservice
    build:
      context: .
      dockerfile: AnalyticsMicroservice/Dockerfile
    ports:
      - "3004:80"
    depends_on:
      - database
    networks:
      vehiclesfleet-logger-net:
        aliases:
          - analytics
  
  database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: mHDyhpoc4336HXuF0GYO
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      MSSQL_TCP_PORT: 1438
      MSSQL_DATABASE: VehiclesFleet
      MSSQL_PASSWORD: mHDyhpoc4336HXuF0GYO
    ports:
      - "1438:1438"
    networks:
      vehiclesfleet-logger-net:

networks:
  vehiclesfleet-logger-net:
    external: true